### ISSUE TITLE
When using gallery, it opens explorer to pick image instead of gallery

### ISSUE THREAD

**Issue by nambv** [FuckBoilerplate/RxPaparazzo#1]
I'm using Android device 5.0, It always opens the explorer to pick image instead of gallery, and I can't pick multiple images. It's very strange
```
RxPaparazzo.takeImages(PhotosPickerFragment.this)
                                    .usingGallery()...

```

**Comment by VictorAlbertos** [comment]
Hi @nambv 

As you can see in the [internal implementation](https://github.com/FuckBoilerplate/RxPaparazzo/blob/master/rx_paparazzo/src/main/java/com/fuck_boilerplate/rx_paparazzo/interactors/PickImage.java#L44), we are just creating an intent to request any available app which would be able to handle images.

We have not experienced that problem, nor in Android 6 or Android 5; with both versions a menu is shown to select the app which you want to perform the action (if several apps are installed on the device).  

But if you have some suggestion to improve the implementation, please let us know. 

Thanks!

**Comment by nambv** [comment]
@VictorAlbertos thank you very much for your reply, but one more thing is, when I pick one image, then I repick this image again the quality of this image is reduced, after pick this image about 10 times, it becomes very bad. Is this a bug?

**Comment by miguelbcr** [comment]
Hi @nambv

I've been testing this behaviour and you are right, there is a bug. We will release a new version asap.

Anyway I'd like to know with which parameters you are launching RxPaparazzo (size, crop, ..) in order to test it in the same scenario.

Thanks!

**Comment by miguelbcr** [comment]
We have released [version 0.0.2](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.0.2)

The problem shoud be fixed at this point.
Please try it out and let us know.

**Comment by nambv** [comment]
@miguelbcr I don't use any params when lauching RxPaparazzo :/
thanks very much for your help! I appreciate a lot!

**Comment by nambv** [comment]
@miguelbcr problem solved, but how can I pick image from gallery instead of explorer, because it is more easier for user to chose image from gallery

**Comment by miguelbcr** [comment]
Hi @nambv 

I've been testing it on Android 5 and 6 and it does not show a chooser, whereas on Android 4 yes.
Anyway on Android 5 and 6 it opens the gallery instead of the file explorer.

You could use the [internal implementation](https://github.com/FuckBoilerplate/RxPaparazzo/blob/master/rx_paparazzo/src/main/java/com/fuck_boilerplate/rx_paparazzo/interactors/PickImage.java#L44) in your own example, launch it and see what happen.

Maybe it's related with an intent parameter but I haven't been able to figure it out. I haven't seen anything related with this on Android docs. Or maybe it is the default behaviour on devices with that Android versions.

You could also use others apps, like twitter, and test what happen. I did it and the result was the same.

Sorry I couldn't help you. If you find something let us know.

**Comment by VictorAlbertos** [comment]
Clogging the issue due to lack of feedback.
