### ISSUE TITLE
Incompatible with Dagger 1

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [FuckBoilerplate/RxPaparazzo#10]
The library uses Dagger 2 and annotation processing for DI. Our main app doesn't use either, rather going for a Dagger 1 and no apt approach. This causes conflicts when compiling because the Transform API detects two instances of Dagger.

While I value the cleanliness provided by DI it may be too opinionated to include it on a library. Given the small scope of the classes I would opt for manual constructor injection instead.

**Comment by VictorAlbertos** [comment]
Hi @FranciscoE-Hudl, sorry about that, but I won't replace dagger by manual constructor injection.  

I think this is a very rare escenario -most people nowadays uses Dagger 2.

Why are you using Dagger 1? Is it a legacy code thing?

**Comment by FranciscoE-Hudl** [comment]
Yes, we have a legacy app, and as most apps on the store it's not running on Dagger 2.

But even if it didn't, annotation processing and retrolambda are dependencies that heavily affect app build time. Even if it's the best at what it does, I can't justify adding the library because of that.

**Comment by VictorAlbertos** [comment]
Have you got any benchmark about using Retrolambda or Dagger 2 as long as annotation processing?

I ask because in my experience I did not notice any downside performance using them on compile time. 

Anyway, I can see your point. But I spent a lot of time making libraries and I’m not willing to loose this technologies, even if some people will not use this libraries because of that.

**Comment by FranciscoE-Hudl** [comment]
I do have my own set of Rx libraries too under http://github.com/pakoito, but can't change my developer convenience for project compatibility. It's not that big of a change either, if you'd accept it as a PR.

**Comment by VictorAlbertos** [comment]
Ok, but please do it in another branch in order to perform the integration test locally before accepting the pull request. 

Thanks :)

**Comment by FranciscoE-Hudl** [comment]
PR request sent: https://github.com/FuckBoilerplate/RxPaparazzo/pull/11

The tests didn't pass in either master or my branch.

**Comment by VictorAlbertos** [comment]
The tests pass, indeed. 

The problem is that you need to run them with a very specific device, due to the use of automator, which performs its interactions with the screen using pixel coordinates. And also the version needs to be Android 5 -in the future we'll try to accommodate the tests to support android devices running Android 6. 

We use the following genymotion emulator, by the way:

Google Nexus 5 5.0.0 API 21 1080x1920 480dpi

Thanks for the pull request. It's very solid and useful :)

The [release 0.1.0](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.1.0) contains the new changes.

**Comment by VictorAlbertos** [comment]
Although, I'm not very enthusiast of using SonarLint to validate my "style" xD 
Why do you use it, exactly?

**Comment by FranciscoE-Hudl** [comment]
I use PMD, or FindBugs, or SonarLint, depending on mood xD The errors and warnings are on my screen and look quite annoying, so I tend to fix them if they're easily accessible, as in a IntelliJ suggestion or similar :P

**Comment by FranciscoE-Hudl** [comment]
Thank you for the merge. I've added you to twitter, feel free to ping me up with anything RxJava, you'll see I'm deep into it too :)

**Comment by VictorAlbertos** [comment]
I'll do that! You too ;)
