### ISSUE TITLE
Should I remove images after retrieving it?

### ISSUE THREAD

**Issue by egslava** [FuckBoilerplate/RxPaparazzo#6]
It seems, like after every picking image from gallery, RzPaparazzo creates new of that image. Should I remove it always or not?

**Comment by miguelbcr** [comment]
Hi @egslava,
We thought that it was the best way, because the library could modify the original image by resizing or cropping it, so the resulting image becomes a new image and we save them into the app name folder on external storage, just like, for example, whatsapp does. 

Anyway, you could delete the image if you don't need it longer by `new File(filepath).delete();` ,for example, after sending it to the server. 

Therefore, remove images or not depends on the app.

**Comment by egslava** [comment]
Thank you for answer! And thank you for your great library! Taking photos from gallery never was so easy :-)
